apiVersion: v1
kind: ReplicationController
metadata:
  name: wf-ticketmonster-rc
  labels:
    name: wildfly
    context: DevOpsDemo
spec:
  replicas: 1
  selector:
    name: wildfly
  template:
    metadata:
      labels:
        name: wildfly
        context: DevOpsDemo
    spec:
      containers:
        - name: wildfly
          image: rafabene/wildfly-ticketmonster
          ports:
            - name: wildfly-port
              containerPort: 8080
              protocol: TCP
            - name: admin-port
              containerPort: 9990
              protocol: TCP
          command: [
                    "sh",
                    "-c",
                    "/opt/jboss/wildfly/bin/standalone.sh -b `hostname --ip-address` -Dpostgres.host=$POSTGRES_SERVICE_HOST -Dpostgres.port=$POSTGRES_SERVICE_PORT"
            ]
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: wildfly
    context: DevOpsDemo
  name: wf-ticketmonster-svc
spec: 
  ports:
  # the port that this service should serve on
  - port: 80
    targetPort: 8080
  # label keys and values that must match in order to receive traffic for this service
  selector: 
    name: wildfly
---
apiVersion: v1
kind: Route
metadata:
  name: wf-ticketmonster-route
spec:
  host: www.timo.com  
  to:
    kind: Service
    name: wf-ticketmonster-svc

