apiVersion: v1
kind: ReplicationController
metadata:
  name: modcluster-replication-controller
  labels:
    name: modcluster
    context: DevOpsDemo
spec:
  replicas: 1
  selector:
    name: modcluster
  template:
    metadata:
      labels:
        name: modcluster
        context: DevOpsDemo
    spec:
      containers:
        - name: modcluster
          image: karm/mod_cluster-master-dockerhub
          env:
            - name: MODCLUSTER_NET
              value: "192.168. 172. 10."
            - name: MODCLUSTER_PORT
              value: "80"
          ports:
            - name: http-port
              containerPort: 80
              protocol: TCP

