apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: modcluster
    context: DevOpsDemo
  name: modcluster
spec: 
  type: NodePort
  ports:
  # the port that this service should serve on
  - port: 80
    name: http-port
    nodePort: 30000
  # label keys and values that must match in order to receive traffic for this service
  selector: 
    name: modcluster